apiVersion: v1
kind: Service
metadata:
  name: {{ include "plutus-telecasting.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "plutus-telecasting.name" . }}
    helm.sh/chart: {{ include "plutus-telecasting.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "plutus-telecasting.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
